### PR TITLE
Adding Ray Tune

### PR DESCRIPTION
**Pull request by richardliaw**
Adding automatic hyperparameter tuning. 

pip install with these instructions! http://ray.readthedocs.io/en/latest/installation.html#trying-the-latest-version-of-ray

### CODE REVIEW

**Comment by xinw1012** [comment]
Is this working now? @richardliaw

**Comment by richardliaw** [comment]
I can't get the `train` to run on my instance of the DL AMI, sadly! (I'm on master without any changes)

```
(pytorch_p36) ubuntu@ip-172-31-43-143:~/skipnet/cifar$ python3 train_rl.py train cifar10_rnn_gate_
rl_110                                                                                            
04-01-18 18:52:start training cifar10_rnn_gate_rl_110                                             
Files already downloaded and verified                                                             
Files already downloaded and verified                                                             
start:  0                                                                                         
04-01-18 18:52:Iter [0] learning rate = 0.0001                                                    
/home/ubuntu/skipnet/cifar/models.py:1267: UserWarning: Implicit dimension choice for softmax has 
been deprecated. Change the call to include dim=X as an argument.                                 
  softmax = self.softmax(x)                                                                       
train_rl.py:32: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change
 the call to include dim=X as an argument.                                                        
  logp = F.log_softmax(x)                                                                         
Traceback (most recent call last):                                                                
  File "train_rl.py", line 493, in <module>                                                       
    main()                                                                                        
  File "train_rl.py", line 121, in main                                                           
    run_training(args)                                                                            
  File "train_rl.py", line 238, in run_training                                                   
    R = r + args.gamma * R                                                                        
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/tensor.py", line
 305, in __add__                                                                                  
    return self.add(other)                                                                        
RuntimeError: invalid argument 3: sizes do not match at /opt/conda/conda-bld/pytorch_1518244421288
/work/torch/lib/THC/generated/../generic/THCTensorMathPointwise.cu:271        
```

**Comment by xinw1012** [comment]
aha, sorry the AMI I sent you has pytorch 0.3 installed.  This CIFAR code was using Pytorch 0.2.0

**Comment by richardliaw** [comment]
Now I'm running into this error; have you seen it before?
```
(pytorch_p36) ubuntu@ip-172-31-4-80:~/skipnet/cifar$ python3 train_rl.py train cifar10_rnn_gate_rl
_110                                                                                              
04-02-18 05:41:start training cifar10_rnn_gate_rl_110                                             
Downloading http://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz to ./data/cifar-10-python.tar.g
z                                                                                                 
Files already downloaded and verified                                                             
start:  0                                                                                         
04-02-18 05:42:Iter [0] learning rate = 0.0001                                                    
Traceback (most recent call last):                                                                
  File "train_rl.py", line 493, in <module>                                                       
    main()                                                                                        
  File "train_rl.py", line 121, in main                                                           
    run_training(args)                                                                            
  File "train_rl.py", line 251, in run_training                                                   
    torch.autograd.backward(gate_saved_actions + [total_loss])                                    
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/autograd/__init_
_.py", line 98, in backward                                                                       
    variables, grad_variables, retain_graph)                                                      
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/autograd/stochas
tic_function.py", line 15, in _do_backward                                                        
    raise RuntimeError("differentiating stochastic functions requires "                           
RuntimeError: differentiating stochastic functions requires providing a reward   
```

**Comment by xinw1012** [comment]
Did you pull the latest repo? I think this issue was solved ...

**Comment by richardliaw** [comment]
This is working now - @xinw1012 you should give it a try!

One main thing is that I had to change the data directory to an absolute path, as each trial has its own directory. Everything else works out of the box

**Comment by xinw1012** [comment]
@richardliaw  This is looking very good!! sorry for the delay on my side.

**Pull request merged**
